version: "3.9"
services:
  db:
    image: mariadb:10.9.3
    ports:
      - "3307:3307"
    volumes:
      - ./db:/var/lib/mysql
    env_file:
      - .env
  adminer:
    image: adminer
    restart: always
    ports:
      - "9999:8080"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"